apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarun-h2db-service
spec:
  selector:
    matchLabels:
      app: tarun-h2db-service
  template:
    metadata:
      labels:
        app: tarun-h2db-service
    spec:
      containers:
      - name: tarun-h2db-service
        image: tarun-h2db-service:v0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9081
        - containerPort: 9082
