version: '3'

services:
  user-service:
    build:
      context: ./user
    image: user-service
    networks:
      - service-network
    ports:
      - "8080:8080" 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - h2-db-service


  booking-service:
    build:
      context: ./booking
    image: booking-service
    networks:
      - service-network
    ports:
      - "8081:8080" 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - h2-db-service


  wallet-service:
    build:
      context: ./wallet
    image: wallet-service
    networks:
      - service-network
    ports:
      - "8082:8080" 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - h2-db-service


  h2-db-service:
    build:
      context: ./h2-db-service
    image: h2-db-service
    networks:
      - service-network
    ports:
      - "9082:9082"
      - "9081:9081" 
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  service-network:
    driver: bridge
