apiVersion: v1
kind: Service
metadata:
  name: h2db-service
spec:
  selector:
    app: h2db
  ports:
  - protocol: TCP
    name: http
    port: 9081
    targetPort: 9081
  - protocol: TCP
    name: tcp
    port: 9082
    targetPort: 9082